# Read the docs here: https://pre-commit.com and http://jorisroovers.github.io/gitlint/
# Install hooks to your clone:
#   $ pre-commit install
#
# List of available hooks: https://pre-commit.com/hooks.html
#

default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
fail_fast: false

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        always_run: true
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
        # ATTENTION This hook doesn't need any files to check.
        # Instead, it checks the whole repo against settings in the
        # `.gitattributes`. So, better to minimize the amount of
        # useless file names passed to it. See also, BUG
        # https://github.com/jumanjihouse/pre-commit-hooks/issues/40
        files: README.md

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: Commit message check
        stages: [commit-msg]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ['--shell=bash', '--color=always']
        files: '\.sh$'
        types: ['file', 'text']
